/**
 * The icons offered in the page editor.
 *
 * A curated set rather than the full pack: the picker's icons are rendered by
 * the public site too, so every name here costs bytes for every visitor. The
 * whole Hugeicons library is 5,448 icons and 863KB gzipped, which is not a
 * reasonable thing to send someone to draw three links.
 *
 * Grouped so the picker can show headings instead of one undifferentiated wall.
 * Every entry is verified against the pack at generation time — see
 * ./iconMap.ts, which must be kept in step.
 */
export interface IconGroup {
  icons: string[];
  label: string;
}

export const ICON_GROUPS: IconGroup[] = [
  {
    icons: [
      "Camera01Icon",
      "Camera02Icon",
      "CameraLensIcon",
      "CameraVideoIcon",
      "Image01Icon",
      "Image02Icon",
      "ImageAdd01Icon",
      "ImageCropIcon",
      "CropIcon",
      "FlashIcon",
      "FilmRoll01Icon",
      "Video01Icon",
      "PlayIcon",
      "AlbumIcon",
      "ImageCompositionIcon",
      "ColorsIcon",
      "PaintBoardIcon",
    ],
    label: "Photography",
  },
  {
    icons: [
      "PenTool01Icon",
      "QuillWrite01Icon",
      "PaintBrush01Icon",
      "PaintBucketIcon",
      "ColorPickerIcon",
      "BrushIcon",
      "Layers01Icon",
      "GridIcon",
      "FrameIcon",
      "MagicWand01Icon",
      "TextIcon",
      "TextFontIcon",
    ],
    label: "Arts & Design",
  },
  {
    icons: [
      "Leaf01Icon",
      "FlowerIcon",
      "Tree01Icon",
      "PineTreeIcon",
      "CloudIcon",
      "SnowIcon",
      "Sun01Icon",
      "Moon02Icon",
      "RainbowIcon",
      "MountainIcon",
      "FireIcon",
      "WaterEnergyIcon",
      "SunriseIcon",
      "SunsetIcon",
      "StarIcon",
      "EarthIcon",
    ],
    label: "Nature & Weather",
  },
  {
    icons: [
      "Airplane01Icon",
      "AirplaneTakeOff01Icon",
      "BicycleIcon",
      "Car01Icon",
      "Bus01Icon",
      "Train01Icon",
      "MapPinIcon",
      "Location01Icon",
      "CompassIcon",
      "GlobeIcon",
      "Building01Icon",
      "Home01Icon",
      "Store01Icon",
      "Hotel01Icon",
      "TentIcon",
      "Luggage01Icon",
      "RoadIcon",
    ],
    label: "Travel & Places",
  },
  {
    icons: [
      "UserIcon",
      "UserMultipleIcon",
      "UserGroupIcon",
      "UserCircleIcon",
      "UserAdd01Icon",
      "FavouriteIcon",
      "SmileIcon",
      "HandshakeIcon",
      "GraduationCapIcon",
      "ChampionIcon",
      "Medal01Icon",
      "Award01Icon",
      "WorkoutRunIcon",
      "BabyBoyDressIcon",
    ],
    label: "People",
  },
  {
    icons: [
      "Mail01Icon",
      "SentIcon",
      "BubbleChatIcon",
      "Message01Icon",
      "TelephoneIcon",
      "SmartPhone01Icon",
      "Call02Icon",
      "Megaphone01Icon",
      "Mic01Icon",
      "HeadsetIcon",
      "Notification01Icon",
      "AtIcon",
      "InstagramIcon",
      "Facebook01Icon",
      "NewTwitterIcon",
      "PinterestIcon",
      "Linkedin01Icon",
      "YoutubeIcon",
      "TiktokIcon",
      "WhatsappIcon",
      "DribbbleIcon",
      "GithubIcon",
      "RssIcon",
    ],
    label: "Communication",
  },
  {
    icons: [
      "File01Icon",
      "FileEditIcon",
      "Note01Icon",
      "NotebookIcon",
      "Book01Icon",
      "Books01Icon",
      "Bookmark01Icon",
      "NewsIcon",
      "Invoice01Icon",
      "Certificate01Icon",
      "Folder01Icon",
      "Archive02Icon",
      "PrinterIcon",
      "Copy01Icon",
      "Attachment01Icon",
    ],
    label: "Documents",
  },
  {
    icons: [
      "ShoppingCart01Icon",
      "ShoppingBag01Icon",
      "CreditCardIcon",
      "Wallet01Icon",
      "GiftIcon",
      "Package01Icon",
      "Tag01Icon",
      "Discount01Icon",
      "DollarCircleIcon",
      "ChartUpIcon",
      "Briefcase01Icon",
    ],
    label: "Commerce",
  },
  {
    icons: [
      "Calendar01Icon",
      "Calendar03Icon",
      "Clock01Icon",
      "TimeQuarterIcon",
      "CheckListIcon",
      "TaskDone01Icon",
      "Target02Icon",
    ],
    label: "Time & Planning",
  },
  {
    icons: [
      "Search01Icon",
      "Add01Icon",
      "MinusSignIcon",
      "Cancel01Icon",
      "Tick02Icon",
      "PencilEdit01Icon",
      "Delete02Icon",
      "Settings01Icon",
      "Menu01Icon",
      "MoreHorizontalIcon",
      "ArrowRight01Icon",
      "ArrowLeft01Icon",
      "ArrowUp01Icon",
      "ArrowDown01Icon",
      "ExternalLinkIcon",
      "Link01Icon",
      "Download01Icon",
      "Upload01Icon",
      "RefreshIcon",
      "FilterIcon",
      "SortByUp01Icon",
      "EyeIcon",
      "ViewOffSlashIcon",
      "LockIcon",
      "Key01Icon",
      "Shield01Icon",
      "InformationCircleIcon",
      "HelpCircleIcon",
      "Alert02Icon",
      "UnavailableIcon",
      "Home02Icon",
      "DashboardSquare01Icon",
    ],
    label: "Interface",
  },
  {
    icons: [
      "LaptopIcon",
      "SmartPhone02Icon",
      "Tablet01Icon",
      "HardDriveIcon",
      "DatabaseIcon",
      "CloudUploadIcon",
      "WifiConnected01Icon",
      "BluetoothIcon",
      "BatteryFullIcon",
      "UsbIcon",
      "CpuIcon",
      "CodeIcon",
      "AiBrain01Icon",
    ],
    label: "Technology",
  },
  {
    icons: [
      "RestaurantIcon",
      "Coffee01Icon",
      "TeaIcon",
      "BeerIcon",
      "IceCream01Icon",
      "MusicNote01Icon",
      "GameController01Icon",
      "PuzzleIcon",
    ],
    label: "Food & Leisure",
  },
];
