import type { IconSvgElement } from "@hugeicons/react";
import {
  Add01Icon,
  AiBrain01Icon,
  Airplane01Icon,
  AirplaneTakeOff01Icon,
  AlbumIcon,
  Alert02Icon,
  Archive02Icon,
  ArrowDown01Icon,
  ArrowLeft01Icon,
  ArrowRight01Icon,
  ArrowUp01Icon,
  AtIcon,
  Attachment01Icon,
  Award01Icon,
  BabyBoyDressIcon,
  BatteryFullIcon,
  BeerIcon,
  BicycleIcon,
  BluetoothIcon,
  Book01Icon,
  Bookmark01Icon,
  Books01Icon,
  Briefcase01Icon,
  BrushIcon,
  BubbleChatIcon,
  Building01Icon,
  Bus01Icon,
  Calendar01Icon,
  Calendar03Icon,
  Call02Icon,
  Camera01Icon,
  Camera02Icon,
  CameraLensIcon,
  CameraVideoIcon,
  Cancel01Icon,
  Car01Icon,
  Certificate01Icon,
  ChampionIcon,
  ChartUpIcon,
  CheckListIcon,
  Clock01Icon,
  CloudIcon,
  CloudUploadIcon,
  CodeIcon,
  Coffee01Icon,
  ColorPickerIcon,
  ColorsIcon,
  CompassIcon,
  Copy01Icon,
  CpuIcon,
  CreditCardIcon,
  CropIcon,
  DashboardSquare01Icon,
  DatabaseIcon,
  Delete02Icon,
  Discount01Icon,
  DollarCircleIcon,
  Download01Icon,
  DribbbleIcon,
  EarthIcon,
  Edit02Icon,
  ExternalLinkIcon,
  EyeIcon,
  Facebook01Icon,
  FavouriteIcon,
  File01Icon,
  FileEditIcon,
  FilmRoll01Icon,
  FilterIcon,
  FireIcon,
  FlashIcon,
  FlowerIcon,
  Folder01Icon,
  FrameIcon,
  GameController01Icon,
  GiftIcon,
  GithubIcon,
  GlobeIcon,
  GraduationCapIcon,
  GridIcon,
  HandshakeIcon,
  HardDriveIcon,
  HeadsetIcon,
  HeartIcon,
  HelpCircleIcon,
  Home01Icon,
  Home02Icon,
  Hotel01Icon,
  IceCream01Icon,
  Image01Icon,
  Image02Icon,
  ImageAdd01Icon,
  ImageCompositionIcon,
  ImageCropIcon,
  InformationCircleIcon,
  InstagramIcon,
  Invoice01Icon,
  Key01Icon,
  LanguageSkillIcon,
  LaptopIcon,
  Layers01Icon,
  Leaf01Icon,
  Link01Icon,
  Linkedin01Icon,
  Location01Icon,
  LockIcon,
  Luggage01Icon,
  MagicWand01Icon,
  Mail01Icon,
  MapPinIcon,
  Medal01Icon,
  Megaphone01Icon,
  Menu01Icon,
  Message01Icon,
  Mic01Icon,
  MinusSignIcon,
  Moon02Icon,
  MoreHorizontalIcon,
  MountainIcon,
  MusicNote01Icon,
  NewsIcon,
  NewTwitterIcon,
  Note01Icon,
  NotebookIcon,
  Notification01Icon,
  Package01Icon,
  PaintBoardIcon,
  PaintBrush01Icon,
  PaintBucketIcon,
  PencilEdit01Icon,
  PenTool01Icon,
  PineTreeIcon,
  PinterestIcon,
  PlayIcon,
  PrinterIcon,
  PuzzleIcon,
  QuestionIcon,
  QuillWrite01Icon,
  RainbowIcon,
  RefreshIcon,
  RestaurantIcon,
  RoadIcon,
  RocketIcon,
  RssIcon,
  Search01Icon,
  SentIcon,
  Settings01Icon,
  Shield01Icon,
  ShoppingBag01Icon,
  ShoppingCart01Icon,
  SmartPhone01Icon,
  SmartPhone02Icon,
  SmileIcon,
  SnowIcon,
  SortByUp01Icon,
  SparklesIcon,
  StarIcon,
  Store01Icon,
  Sun01Icon,
  SunriseIcon,
  SunsetIcon,
  Tablet01Icon,
  Tag01Icon,
  Target02Icon,
  TaskDone01Icon,
  TeaIcon,
  TelephoneIcon,
  TentIcon,
  TextFontIcon,
  TextIcon,
  Tick02Icon,
  TiktokIcon,
  TimeQuarterIcon,
  Train01Icon,
  Tree01Icon,
  UnavailableIcon,
  Upload01Icon,
  UsbIcon,
  UserAdd01Icon,
  UserCircleIcon,
  UserGroupIcon,
  UserIcon,
  UserMultipleIcon,
  Video01Icon,
  ViewOffSlashIcon,
  Wallet01Icon,
  WaterEnergyIcon,
  WhatsappIcon,
  WifiConnected01Icon,
  WorkoutRunIcon,
  YoutubeIcon,
} from "@hugeicons-pro/core-stroke-standard";

/** One icon's drawing data, as HugeiconsIcon's `icon` prop takes it. */
export type IconComponent = IconSvgElement;

/**
 * Every icon the picker offers, plus the names older pages already store.
 *
 * Named imports rather than `import * as`: a namespace import cannot be
 * tree-shaken, so a dynamic lookup off one would pull all 5,448 icons into the
 * bundle to support the 185 that are selectable.
 *
 * The second block is aliases. Those keys are Iconoir names from before the
 * icon pack changed, and they are what is stored in the database against
 * existing pages — dropping one would blank the icon on a live page.
 *
 * Generated from ICON_GROUPS in ./icons.ts — keep the two in step.
 */
export const ICON_COMPONENTS: Record<string, IconComponent> = {
  Add01Icon,
  AiBrain01Icon,

  // Legacy names, kept resolvable.
  Airplane: Airplane01Icon,
  Airplane01Icon,
  AirplaneTakeOff01Icon,
  AlbumIcon,
  Alert02Icon,
  Archive02Icon,
  ArrowDown01Icon,
  ArrowLeft01Icon,
  ArrowRight01Icon,
  ArrowUp01Icon,
  AtIcon,
  Attachment01Icon,
  Award01Icon,
  BabyBoyDressIcon,
  BatteryFullIcon,
  BeerIcon,
  Bicycle: BicycleIcon,
  BicycleIcon,
  BluetoothIcon,
  Book: Book01Icon,
  Book01Icon,
  Bookmark: Bookmark01Icon,
  Bookmark01Icon,
  BookStack: Books01Icon,
  Books01Icon,
  Briefcase01Icon,
  BrushIcon,
  BubbleChatIcon,
  Building: Building01Icon,
  Building01Icon,
  Bus01Icon,
  Calendar: Calendar01Icon,
  Calendar01Icon,
  Calendar03Icon,
  Call02Icon,
  Camera: Camera01Icon,
  Camera01Icon,
  Camera02Icon,
  CameraLensIcon,
  CameraVideoIcon,
  Cancel01Icon,
  Car: Car01Icon,
  Car01Icon,
  Cart: ShoppingCart01Icon,
  Certificate01Icon,
  ChampionIcon,
  ChartUpIcon,
  ChatBubble: BubbleChatIcon,
  CheckListIcon,
  Clock: Clock01Icon,
  Clock01Icon,
  Cloud: CloudIcon,
  CloudIcon,
  CloudUploadIcon,
  CodeIcon,
  Coffee01Icon,
  ColorFilter: ColorsIcon,
  ColorPickerIcon,
  ColorsIcon,
  Community: UserGroupIcon,
  Compass: CompassIcon,
  CompassIcon,
  Copy01Icon,
  CpuIcon,
  CreditCard: CreditCardIcon,
  CreditCardIcon,
  Crop: CropIcon,
  CropIcon,
  Cutlery: RestaurantIcon,
  DashboardSquare01Icon,
  DatabaseIcon,
  Delete02Icon,
  DesignNib: PenTool01Icon,
  Discount01Icon,
  DollarCircleIcon,
  Download01Icon,
  DribbbleIcon,
  EarthIcon,
  Edit: Edit02Icon,
  ExternalLinkIcon,
  Eye: EyeIcon,
  EyeIcon,
  Facebook01Icon,
  FavouriteIcon,
  File01Icon,
  FileEditIcon,
  FilmRoll01Icon,
  FilterIcon,
  FireIcon,
  Flash: FlashIcon,
  FlashIcon,
  Flower: FlowerIcon,
  FlowerIcon,
  Folder01Icon,
  Frame: FrameIcon,
  FrameIcon,
  GameController01Icon,
  Gift: GiftIcon,
  GiftIcon,
  GithubIcon,
  Globe: GlobeIcon,
  GlobeIcon,
  GraduationCap: GraduationCapIcon,
  GraduationCapIcon,
  GridIcon,
  Group: UserMultipleIcon,
  HalfMoon: Moon02Icon,
  HandshakeIcon,
  HardDriveIcon,
  Headset: HeadsetIcon,
  HeadsetIcon,
  Heart: HeartIcon,
  HelpCircleIcon,
  Home: Home01Icon,
  Home01Icon,
  Home02Icon,
  Hotel01Icon,
  IceCream01Icon,
  Image01Icon,
  Image02Icon,
  ImageAdd01Icon,
  ImageCompositionIcon,
  ImageCropIcon,
  InfoCircle: InformationCircleIcon,
  InformationCircleIcon,
  InstagramIcon,
  Invoice01Icon,
  Journal: NotebookIcon,
  Key: Key01Icon,
  Key01Icon,
  Language: LanguageSkillIcon,
  LaptopIcon,
  Layers01Icon,
  Leaf: Leaf01Icon,
  Leaf01Icon,
  Link: Link01Icon,
  Link01Icon,
  Linkedin01Icon,
  Location01Icon,
  Lock: LockIcon,
  LockIcon,
  Luggage01Icon,
  MagicWand01Icon,
  Mail: Mail01Icon,
  Mail01Icon,
  MapPin: MapPinIcon,
  MapPinIcon,
  Medal: Medal01Icon,
  Medal01Icon,
  MediaImage: Image01Icon,
  MediaImagePlus: ImageAdd01Icon,
  Megaphone: Megaphone01Icon,
  Megaphone01Icon,
  Menu01Icon,
  Message01Icon,
  Mic01Icon,
  Microphone: Mic01Icon,
  MinusSignIcon,
  Moon02Icon,
  MoreHorizontalIcon,
  MountainIcon,
  MusicNote01Icon,
  NewsIcon,
  NewTwitterIcon,
  Note01Icon,
  NotebookIcon,
  Notes: Note01Icon,
  Notification01Icon,
  Package: Package01Icon,
  Package01Icon,
  Page: File01Icon,
  PaintBoardIcon,
  PaintBrush01Icon,
  PaintBucketIcon,
  Palette: PaintBoardIcon,
  PencilEdit01Icon,
  PenTool01Icon,
  Phone: TelephoneIcon,
  PineTreeIcon,
  PinterestIcon,
  PlayIcon,
  Printer: PrinterIcon,
  PrinterIcon,
  Puzzle: PuzzleIcon,
  PuzzleIcon,
  QuestionMark: QuestionIcon,
  QuillWrite01Icon,
  RainbowIcon,
  RefreshIcon,
  RestaurantIcon,
  RoadIcon,
  Rocket: RocketIcon,
  RssIcon,
  Running: WorkoutRunIcon,
  Search: Search01Icon,
  Search01Icon,
  Send: SentIcon,
  SentIcon,
  Settings01Icon,
  Shield: Shield01Icon,
  Shield01Icon,
  Shop: Store01Icon,
  ShoppingBag01Icon,
  ShoppingCart01Icon,
  SmartPhone01Icon,
  SmartPhone02Icon,
  SmileIcon,
  Snow: SnowIcon,
  SnowIcon,
  SortByUp01Icon,
  Sparks: SparklesIcon,
  Star: StarIcon,
  StarIcon,
  Store01Icon,
  Suitcase: Briefcase01Icon,
  Sun01Icon,
  SunLight: Sun01Icon,
  SunriseIcon,
  SunsetIcon,
  Tablet01Icon,
  Tag01Icon,
  Target02Icon,
  TaskDone01Icon,
  TeaIcon,
  TelephoneIcon,
  TentIcon,
  TextFontIcon,
  TextIcon,
  Tick02Icon,
  TiktokIcon,
  TimeQuarterIcon,
  Train01Icon,
  Tree: Tree01Icon,
  Tree01Icon,
  Trophy: ChampionIcon,
  UnavailableIcon,
  Upload01Icon,
  UsbIcon,
  User: UserIcon,
  UserAdd01Icon,
  UserCircleIcon,
  UserGroupIcon,
  UserIcon,
  UserMultipleIcon,
  Video01Icon,
  VideoCamera: Video01Icon,
  ViewOffSlashIcon,
  Wallet: Wallet01Icon,
  Wallet01Icon,
  WaterEnergyIcon,
  WhatsappIcon,
  WifiConnected01Icon,
  WorkoutRunIcon,
  YoutubeIcon,
};
