import type { IconSvgElement } from "@hugeicons/react";
import {
  Airplane01Icon,
  BicycleIcon,
  Book01Icon,
  Bookmark01Icon,
  Books01Icon,
  Briefcase01Icon,
  BubbleChatIcon,
  Building01Icon,
  Calendar01Icon,
  Camera01Icon,
  Car01Icon,
  ChampionIcon,
  Clock01Icon,
  CloudIcon,
  ColorsIcon,
  CompassIcon,
  CreditCardIcon,
  CropIcon,
  Edit02Icon,
  EyeIcon,
  File01Icon,
  FlashIcon,
  FlowerIcon,
  FrameIcon,
  GiftIcon,
  GlobeIcon,
  GraduationCapIcon,
  HeadsetIcon,
  HeartIcon,
  Home01Icon,
  Image01Icon,
  ImageAdd01Icon,
  InformationCircleIcon,
  Key01Icon,
  LanguageSkillIcon,
  Leaf01Icon,
  Link01Icon,
  LockIcon,
  Mail01Icon,
  MapPinIcon,
  Medal01Icon,
  Megaphone01Icon,
  Mic01Icon,
  Moon02Icon,
  Note01Icon,
  NotebookIcon,
  Package01Icon,
  PaintBoardIcon,
  PenTool01Icon,
  PrinterIcon,
  PuzzleIcon,
  QuestionIcon,
  RestaurantIcon,
  RocketIcon,
  Search01Icon,
  SentIcon,
  Shield01Icon,
  ShoppingCart01Icon,
  SnowIcon,
  SparklesIcon,
  StarIcon,
  Store01Icon,
  Sun01Icon,
  TelephoneIcon,
  Tree01Icon,
  UserGroupIcon,
  UserIcon,
  UserMultipleIcon,
  Video01Icon,
  Wallet01Icon,
  WorkoutRunIcon,
} from "@hugeicons-pro/core-stroke-standard";

/** One icon's drawing data, as HugeiconsIcon's `icon` prop takes it. */
export type IconComponent = IconSvgElement;

/**
 * Explicit map of the icons the picker offers.
 *
 * Deliberately named imports rather than `import * as Icons`. A namespace
 * import cannot be tree-shaken, so looking icons up dynamically off one pulled
 * every icon in the pack into the entry bundle to support the 71 that are
 * actually selectable.
 *
 * The keys are the names stored in the database against a page, so they stay
 * exactly as they were when these were Iconoir components — only what they
 * point at has changed. Renaming one would blank the icon on every page already
 * using it.
 *
 * Generated from ICON_GROUPS in ./icons.ts — keep the two in step.
 */
export const ICON_COMPONENTS: Record<string, IconComponent> = {
  Airplane: Airplane01Icon,
  Bicycle: BicycleIcon,
  Book: Book01Icon,
  Bookmark: Bookmark01Icon,
  BookStack: Books01Icon,
  Building: Building01Icon,
  Calendar: Calendar01Icon,
  Camera: Camera01Icon,
  Car: Car01Icon,
  Cart: ShoppingCart01Icon,
  ChatBubble: BubbleChatIcon,
  Clock: Clock01Icon,
  Cloud: CloudIcon,
  ColorFilter: ColorsIcon,
  Community: UserGroupIcon,
  Compass: CompassIcon,
  CreditCard: CreditCardIcon,
  Crop: CropIcon,
  Cutlery: RestaurantIcon,
  DesignNib: PenTool01Icon,
  Edit: Edit02Icon,
  Eye: EyeIcon,
  Flash: FlashIcon,
  Flower: FlowerIcon,
  Frame: FrameIcon,
  Gift: GiftIcon,
  Globe: GlobeIcon,
  GraduationCap: GraduationCapIcon,
  Group: UserMultipleIcon,
  HalfMoon: Moon02Icon,
  Headset: HeadsetIcon,
  Heart: HeartIcon,
  Home: Home01Icon,
  InfoCircle: InformationCircleIcon,
  Journal: NotebookIcon,
  Key: Key01Icon,
  Language: LanguageSkillIcon,
  Leaf: Leaf01Icon,
  Link: Link01Icon,
  Lock: LockIcon,
  Mail: Mail01Icon,
  MapPin: MapPinIcon,
  Medal: Medal01Icon,
  MediaImage: Image01Icon,
  MediaImagePlus: ImageAdd01Icon,
  Megaphone: Megaphone01Icon,
  Microphone: Mic01Icon,
  Notes: Note01Icon,
  Package: Package01Icon,
  Page: File01Icon,
  Palette: PaintBoardIcon,
  Phone: TelephoneIcon,
  Printer: PrinterIcon,
  Puzzle: PuzzleIcon,
  QuestionMark: QuestionIcon,
  Rocket: RocketIcon,
  Running: WorkoutRunIcon,
  Search: Search01Icon,
  Send: SentIcon,
  Shield: Shield01Icon,
  Shop: Store01Icon,
  Snow: SnowIcon,
  Sparks: SparklesIcon,
  Star: StarIcon,
  Suitcase: Briefcase01Icon,
  SunLight: Sun01Icon,
  Tree: Tree01Icon,
  Trophy: ChampionIcon,
  User: UserIcon,
  VideoCamera: Video01Icon,
  Wallet: Wallet01Icon,
};
