import type { ReactNode } from "react";
import {
  createContext,
  useCallback,
  useContext,
  useEffect,
  useMemo,
  useState,
} from "react";
import {
  defaultSiteSettings,
  type ResolvedSiteSettings,
} from "../../config/siteSettings";
import { findFont } from "../../config/theme";
import { settingsApi } from "../services/portfolioService";
import { siteConfig } from "../site";
import { loadFont } from "./fonts";

interface SiteSettingsContextValue {
  /** True until the first fetch settles; the built-in defaults render meanwhile. */
  isLoading: boolean;
  reload: () => Promise<void>;
  /** Replaces the active settings after an admin saves, with no refetch. */
  setSettings: (next: ResolvedSiteSettings) => void;
  settings: ResolvedSiteSettings;
}

const SiteSettingsContext = createContext<SiteSettingsContextValue | null>(
  null
);

/**
 * Applies the theme by overriding the custom properties Tailwind's @theme block
 * already declares, so every existing `bg-background` / `text-foreground` /
 * `font-sans` utility follows along without touching a component.
 *
 * This is why the theme is stored as colors rather than Tailwind class names:
 * utilities are generated by scanning source at build time, so a class that
 * exists only in a database row would never be emitted.
 */
const applyTheme = (settings: ResolvedSiteSettings): void => {
  const { theme } = settings;
  const root = document.documentElement;

  root.style.setProperty("--color-background", theme.background);
  root.style.setProperty("--color-foreground", theme.foreground);
  root.style.setProperty("--color-accent", theme.accent);

  const sans = findFont(theme.sansFont);
  const serif = findFont(theme.serifFont);
  if (sans) {
    root.style.setProperty("--font-sans", sans.stack);
  }
  if (serif) {
    root.style.setProperty("--font-serif", serif.stack);
  }

  void loadFont(theme.sansFont);
  void loadFont(theme.serifFont);

  document
    .querySelector('meta[name="theme-color"]')
    ?.setAttribute("content", theme.background);
};

export function SiteSettingsProvider({ children }: { children: ReactNode }) {
  // First paint uses the values compiled into the bundle, so the page is never
  // blank and never unstyled while the request is in flight.
  const [settings, setSettingsState] = useState<ResolvedSiteSettings>(() =>
    defaultSiteSettings(siteConfig)
  );
  const [isLoading, setIsLoading] = useState(true);

  const setSettings = useCallback((next: ResolvedSiteSettings) => {
    setSettingsState(next);
    applyTheme(next);
    document.title = next.name;
  }, []);

  const reload = useCallback(async () => {
    try {
      const fetched = await settingsApi.get();
      // A 200 carrying the wrong shape — a stale cache, a partial deploy, an
      // intercepting proxy — must not take the site down. applyTheme reads
      // theme.background directly, so an absent theme would throw during
      // render and leave a blank page.
      if (!fetched.theme) {
        throw new Error("Site settings response is missing a theme");
      }
      setSettings(fetched);
    } catch {
      // Keep whatever is already rendering: stale settings beat no site.
    } finally {
      setIsLoading(false);
    }
  }, [setSettings]);

  // Paints the compiled defaults immediately, then fetches the live values.
  //
  // This must not depend on `settings`. reload() replaces them with a freshly
  // parsed object, so a `settings` dependency re-runs the effect, which fetches
  // again, forever — a request loop that hammers the API for as long as the tab
  // is open. Reading the defaults straight from the module keeps the dependency
  // list honest rather than suppressed: on mount `settings` IS this value, and
  // reload() re-applies the theme once the response lands.
  useEffect(() => {
    applyTheme(defaultSiteSettings(siteConfig));
    void reload();
  }, [reload]);

  const value = useMemo(
    () => ({ isLoading, reload, setSettings, settings }),
    [settings, isLoading, setSettings, reload]
  );

  return (
    <SiteSettingsContext.Provider value={value}>
      {children}
    </SiteSettingsContext.Provider>
  );
}

/** Live site settings. Falls back to compiled defaults outside the provider. */
export const useSiteSettings = (): SiteSettingsContextValue => {
  const ctx = useContext(SiteSettingsContext);
  if (ctx) {
    return ctx;
  }
  return {
    isLoading: false,
    reload: async () => undefined,
    setSettings: () => undefined,
    settings: defaultSiteSettings(siteConfig),
  };
};
