/**
 * What each fal endpoint will accept, read from fal's own OpenAPI schemas.
 *
 * GENERATED by scripts/fetch-fal-params.py. Do not edit by hand — re-run the
 * script after adding a model in /admin/models.
 *
 * This exists because fal validates strictly and bills first: a field an
 * endpoint has never heard of comes back 422 on a request that has already been
 * paid for. The panel offers size, output format and quality; which of those an
 * endpoint takes, under which name, and with which values, differs per endpoint
 * in ways that are not guessable — Kontext takes `aspect_ratio` where Ideogram
 * takes `image_size`, FLUX accepts only jpeg and png where Nano Banana also
 * takes webp, and a vectoriser takes none of it.
 *
 * A hand-written version of this table had four errors. This one is read from
 * the source.
 *
 * An endpoint absent from this table accepts none of these parameters, which is
 * the safe reading: applyParams sends nothing it cannot find here.
 */

/** Field name to the values that field allows. */
export type FalParamSupport = Readonly<Record<string, readonly string[]>>;

export const FAL_PARAM_SUPPORT: Readonly<Record<string, FalParamSupport>> =
  {
  "bytedance/seedance-2.0/fast/image-to-video": {
    "aspect_ratio": [
      "16:9",
      "1:1",
      "21:9",
      "3:4",
      "4:3",
      "9:16",
      "auto"
    ]
  },
  "bytedance/seedance-2.5/image-to-video": {
    "aspect_ratio": []
  },
  "fal-ai/birefnet/v2": {
    "output_format": [
      "gif",
      "png",
      "webp"
    ]
  },
  "fal-ai/flux-lora": {
    "image_size": [
      "landscape_16_9",
      "landscape_4_3",
      "portrait_16_9",
      "portrait_4_3",
      "square",
      "square_hd"
    ],
    "num_inference_steps": [],
    "output_format": [
      "jpeg",
      "png"
    ]
  },
  "fal-ai/flux-lora/image-to-image": {
    "image_size": [
      "landscape_16_9",
      "landscape_4_3",
      "portrait_16_9",
      "portrait_4_3",
      "square",
      "square_hd"
    ],
    "num_inference_steps": [],
    "output_format": [
      "jpeg",
      "png"
    ]
  },
  "fal-ai/flux-lora/inpainting": {
    "image_size": [
      "landscape_16_9",
      "landscape_4_3",
      "portrait_16_9",
      "portrait_4_3",
      "square",
      "square_hd"
    ],
    "num_inference_steps": [],
    "output_format": [
      "jpeg",
      "png"
    ]
  },
  "fal-ai/flux-pro/kontext": {
    "aspect_ratio": [
      "16:9",
      "1:1",
      "21:9",
      "2:3",
      "3:2",
      "3:4",
      "4:3",
      "9:16",
      "9:21"
    ],
    "output_format": [
      "jpeg",
      "png"
    ]
  },
  "fal-ai/flux-pro/kontext/max": {
    "aspect_ratio": [
      "16:9",
      "1:1",
      "21:9",
      "2:3",
      "3:2",
      "3:4",
      "4:3",
      "9:16",
      "9:21"
    ],
    "output_format": [
      "jpeg",
      "png"
    ]
  },
  "fal-ai/flux/dev": {
    "image_size": [
      "landscape_16_9",
      "landscape_4_3",
      "portrait_16_9",
      "portrait_4_3",
      "square",
      "square_hd"
    ],
    "num_inference_steps": [],
    "output_format": [
      "jpeg",
      "png"
    ]
  },
  "fal-ai/flux/dev/image-to-image": {
    "num_inference_steps": [],
    "output_format": [
      "jpeg",
      "png"
    ]
  },
  "fal-ai/ideogram/v3": {
    "image_size": [
      "landscape_16_9",
      "landscape_4_3",
      "portrait_16_9",
      "portrait_4_3",
      "square",
      "square_hd"
    ]
  },
  "fal-ai/krea-2/turbo": {
    "image_size": [
      "landscape_16_9",
      "landscape_4_3",
      "portrait_16_9",
      "portrait_4_3",
      "square",
      "square_hd"
    ],
    "output_format": [
      "jpeg",
      "png"
    ]
  },
  "fal-ai/krea-2/turbo/image-to-image": {
    "image_size": [
      "auto",
      "landscape_16_9",
      "landscape_4_3",
      "portrait_16_9",
      "portrait_4_3",
      "square",
      "square_hd"
    ],
    "output_format": [
      "jpeg",
      "png"
    ]
  },
  "fal-ai/nano-banana-pro": {
    "aspect_ratio": [
      "16:9",
      "1:1",
      "21:9",
      "2:3",
      "3:2",
      "3:4",
      "4:3",
      "4:5",
      "5:4",
      "9:16",
      "auto"
    ],
    "output_format": [
      "jpeg",
      "png",
      "webp"
    ]
  },
  "fal-ai/nano-banana/edit": {
    "aspect_ratio": [
      "16:9",
      "1:1",
      "21:9",
      "2:3",
      "3:2",
      "3:4",
      "4:3",
      "4:5",
      "5:4",
      "9:16",
      "auto"
    ],
    "output_format": [
      "jpeg",
      "png",
      "webp"
    ]
  },
  "fal-ai/recraft/v4.1/text-to-vector": {
    "image_size": [
      "landscape_16_9",
      "landscape_4_3",
      "portrait_16_9",
      "portrait_4_3",
      "square",
      "square_hd"
    ]
  },
  "fal-ai/recraft/v4/pro/text-to-vector": {
    "image_size": [
      "landscape_16_9",
      "landscape_4_3",
      "portrait_16_9",
      "portrait_4_3",
      "square",
      "square_hd"
    ]
  },
  "fal-ai/veo3.1/fast/image-to-video": {
    "aspect_ratio": [
      "16:9",
      "9:16",
      "auto"
    ]
  },
  "fal-ai/veo3.1/image-to-video": {
    "aspect_ratio": [
      "16:9",
      "9:16",
      "auto"
    ]
  },
  "fal-ai/veo3.1/lite/image-to-video": {
    "aspect_ratio": [
      "16:9",
      "9:16",
      "auto"
    ]
  },
  "ideogram/v4/image-to-image": {
    "image_size": [
      "auto",
      "landscape_16_9",
      "landscape_4_3",
      "portrait_16_9",
      "portrait_4_3",
      "square",
      "square_hd"
    ],
    "output_format": [
      "jpeg",
      "png"
    ]
  },
  "ideogram/v4/instant": {
    "image_size": [
      "landscape_16_9",
      "landscape_4_3",
      "portrait_16_9",
      "portrait_4_3",
      "square",
      "square_hd"
    ],
    "output_format": [
      "jpeg",
      "png"
    ]
  },
  "openai/gpt-image-2": {
    "image_size": [
      "auto",
      "landscape_16_9",
      "landscape_4_3",
      "portrait_16_9",
      "portrait_4_3",
      "square",
      "square_hd"
    ],
    "output_format": [
      "jpeg",
      "png",
      "webp"
    ],
    "quality": [
      "auto",
      "high",
      "low",
      "medium"
    ]
  },
  "openai/gpt-image-2/edit": {
    "image_size": [
      "auto",
      "landscape_16_9",
      "landscape_4_3",
      "portrait_16_9",
      "portrait_4_3",
      "square",
      "square_hd"
    ],
    "output_format": [
      "jpeg",
      "png",
      "webp"
    ],
    "quality": [
      "auto",
      "high",
      "low",
      "medium"
    ]
  }
} as const;
